# Generated by Django 2.2.2 on 2020-07-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15, null=True)),
                ('description', models.CharField(max_length=30, null=True)),
                ('did', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
