# Generated by Django 2.2.2 on 2019-06-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Indra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='report_type',
            new_name='reporttype',
        ),
    ]
