# Generated by Django 2.2.2 on 2019-06-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indra', '0002_auto_20190614_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
